package menu

import (
	"github.com/darkhz/invidtui/ui/app"
)

// Items describes the menu items.
var Items = &app.MenuData{
	Items: map[string][]string{
		"App": {
			"Dashboard",
			"Cancel",
			"Suspend",
			"DownloadView",
			"DownloadOptions",
			"InstancesList",
			"Quit",
		},
		"Start": {
			"SearchQuery",
		},
		"Files": {
			"FilebrowserDirForward",
			"FilebrowserDirBack",
			"FilebrowserToggleHidden",
			"Exit",
		},
		"Playlist": {
			"Comments",
			"Link",
			"Add",
			"Remove",
			"LoadMore",
			"DownloadOptions",
			"Exit",
		},
		"Comments": {
			"CommentReplies",
			"Exit",
		},
		"Downloads": {
			"DownloadOptionSelect",
			"DownloadCancel",
			"Exit",
		},
		"Search": {
			"SearchStart",
			"SearchQuery",
			"LoadMore",
			"SearchSwitchMode",
			"SearchSuggestions",
			"SearchParameters",
			"Comments",
			"Link",
			"Playlist",
			"ChannelVideos",
			"ChannelPlaylists",
			"Add",
			"DownloadOptions",
		},
		"Channel": {
			"Switch",
			"LoadMore",
			"SearchQuery",
			"Playlist",
			"Add",
			"Comments",
			"Link",
			"DownloadOptions",
			"Exit",
		},
		"Dashboard": {
			"Switch",
			"DashboardReload",
			"LoadMore",
			"Add",
			"Comments",
			"Playlist",
			"DashboardCreatePlaylist",
			"DashboardEditPlaylist",
			"ChannelVideos",
			"ChannelPlaylists",
			"Remove",
			"Exit",
		},
		"Player": {
			"PlayerOpenPlaylist",
			"Queue",
			"PlayerHistory",
			"PlayerInfo",
			"PlayerQueueAudio",
			"PlayerQueueVideo",
			"PlayerPlayAudio",
			"PlayerPlayVideo",
			"AudioURL",
			"VideoURL",
		},
		"Queue": {
			"QueuePlayMove",
			"QueueSave",
			"QueueAppend",
			"QueueDelete",
			"QueueMove",
			"Exit",
		},
		"History": {
			"SearchQuery",
			"ChannelVideos",
			"ChannelPlaylists",
			"Exit",
		},
	},
	Visible: map[string]func(menuType string) bool{
		"DownloadView":      downloadView,
		"DownloadOptions":   downloadOptions,
		"Comments":          isVideo,
		"Link":              isVideo,
		"DownloadCancel":    downloadViewVisible,
		"Add":               add,
		"Remove":            remove,
		"Playlist":          isPlaylist,
		"ChannelVideos":     isChannel,
		"ChannelPlaylists":  isChannel,
		"SearchQuery":       query,
		"SearchStart":       searchInputFocused,
		"SearchSwitchMode":  searchInputFocused,
		"SearchSuggestions": searchInputFocused,
		"SearchParameters":  searchInputFocused,
		"Reload":            isDashboardFocused,
		"Create":            createPlaylist,
		"Edit":              editPlaylist,
		"Queue":             playerQueue,
		"PlayerInfo":        infoShown,
		"PlayerQueueAudio":  isVideo,
		"PlayerQueueVideo":  isVideo,
		"PlayerPlayAudio":   isVideo,
		"PlayerPlayVideo":   isVideo,
	},
}
